export const BlogsData = [
  {
    id: 1,
    title: "How you invest your time is just as important as how you invest your money",
    author: "Allison Baum Gates",
    summary: "You can spend a lot of time searching for something, but if you’re looking in the wrong places, you’ll never find it.",
    postContent: " I had been investing my time in meeting with local entrepreneurs, a strategy that wasn’t producing results. Clearly there was a light shining directly in front of me in Hong Kong, but I had a feeling my keys were across the street in a park somewhere. I knew I had to stop doing what was easy and start looking beyond Hong Kong for deal flow. Along with my business partner, I began to spend my time researching the major hubs of entrepreneurial and tech activity that had a high concentration of entrepreneurs seeking funding. I also hunted for those who had produced big outcomes in the past decade (unlike Hong Kong, which was still early in its journey as a startup ecosystem and did not have as many examples of successful venture-backed businesses). Then I hit the road  My partner and I spent time in cities like San Francisco, Austin, and New York, as well as London, Beijing, and Singapore. I spent the better part of my first five years in venture capital on a plane (mostly in middle seats in economy, to be exact). On each trip, I was energized by the entrepreneurial buzz in each region we visited and overwhelmed by the number of promising companies we met in each place. My days were equally jam-packed, if not more so, than my time at home. However, unlike my experience in Hong Kong, each day of meetings was yielding exciting investment opportunities that I was eager to dig into. Time flew by, and I was finally producing results. I had real deal flow! I just had to get on a plane to go get it ",
    img: "https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1218283510.jpg?w=430&h=230&crop=1"

  },
  {
    id: 2,
   title: "Andreessen Horowitz is now openly courting capital from Saudi Arabia, despite U.S. strains",
    author: "Connie Loizos",
    summary: "Andreessen Horowitz is now openly courting capital from Saudi Arabia, despite U.S. strains. According to Bloomberg, Marc Andreessen and Ben Horowitz appeared on stage with WeWork co-founder Adam Ne...",
    postContent: " According to Bloomberg, Marc Andreessen and Ben Horowitz appeared on stage with WeWork co-founder Adam Neumann to talk for at least the second time since November about their firm’s $350 million investment in Flow, which is Neumann’s new residential real estate company. Their choice of venue was intentional: the conference was organized by a nonprofit backed by one of Saudi Arabia’s largest sovereign funds, and Flow may launch in the Kingdom, says Bloomberg. Meanwhile, the three reportedly laid it on thick, with Horowitz praising Saudi Arabia as a “startup country” and saying that “Saudi has a founder; you don’t call him a founder, you call him his royal highness.”Said Neumann separately: “It’s leaders like his royal highness that are actually going to lead us where we want to go.”We reached out to Andreessen Horowitz with related questions this morning and have yet to hear back.That a firm of Andreessen Horowitz’s size and interests is looking to cement relationships in Saudi Arabia isn’t shocking. Though the 14-year-old outfit has never made public who its limited partners are, no one would grab at their pearls were it revealed that sovereign wealth funds from the region have helped boost the assets under management at the firm to $35 billion across its many funds. Indeed, back in October, Horowitz spoke at the investment conference dubbed “Davos in the Desert,” which is often a clue that someone is fundraising.",
    img: " https://techcrunch.com/wp-content/uploads/2023/04/Screen-Shot-2023-04-01-at-5.07.55-PM.png?w=430&h=230&crop=1"
  },
  {
    id: 3,
    title: "This Week in Apps: WWDC23, ByteDance pushes Lemon8 ahead of TikTok ban, T2 capitalizes on Twitter chaos",
    author: "Sarah Perez",
    summary: "Welcome back to This Week in Apps, the weekly TechCrunch series that recaps the latest in mobile OS news, mobile applications and the overall app economy. The app economy in 2023 hit a few snags, a...",
    postContent: "As expected, Apple announced its plans for this year’s Worldwide Developers Conference (WWDC). The big event will return to Apple Park in Cupertino on June 5-9. However, the event looks like it will still be another scaled-down version, similar to last year, with its keynote and State of the Union again livestreamed.Apple also noted it will host a special all-day event for developers and students on June 5. And, as in previous years, developers will be able to meet some of the teams at Apple, celebrate top apps at the Apple Design Awards ceremony and enjoy various evening activities. Student developers will also participate in a Swift Student Challenge competition, which could win them WWDC23 outerwear, AirPods Pro, a customized pin set and a one-year membership to the Apple Developer Program. The deadline to apply is April 19.The company will continue to post WWDC announcements leading up to and during the conference, so keep an eye on your inboxes and the Apple Developer app for updates.The big question on everyone’s minds is whether or not Apple will present its AR/VR headset during WWDC this year. Various reports have suggested mass production on the device has been pushed back a couple of months to the third quarter of 2023. Plus, a concerning report by The New York Times indicated the device is among the first to generate rare, internal dissent among Apple employees — some of whom don’t believe it’s a fit for the company. Expected to be priced at $3,000, some are worried about its utility and the still unproven market. Still, Bloomberg is betting on a headset reveal and the accompanying xrOS software.",
    img : "https://techcrunch.com/wp-content/uploads/2023/02/this-week-in-apps-splash-2023.webp?w=430&h=230&crop=1"
  },
  {
    id: 4,
  title: "Netflix restructures its film units, aiming to make fewer (but better) original movies",
    author: "Aisha Malik",
    summary: "Netflix is restructuring its film units and vowing to make fewer but better movies, according to a new report from Bloomberg, which Netflix partially confirmed. The report said the streaming giant ...",
    postContent: " Netflix is restructuring its film units and vowing to make fewer but better movies, according to a new report from Bloomberg, which Netflix partially confirmed. The report said the streaming giant is combining film units that produce small and midsize films, resulting in a handful of layoffs, including two longtime executives. Netflix told TechCrunch that these changes were made to simplify its structure and set it up for the next phase of its growth, but declined to comment on how many people were being let go. Scott Stuber, chairman of Netflix Film, has been looking to scale back the company’s output of films to ensure that more of them are high quality, according to the report.It appears that this change has already been implemented, as the report comes as Netflix recently revealed its 2023 original films lineup, which consists of 49 titles. In comparison, the company had 85 original films in its lineup last year. For context, a Netflix original refers to both the content that has been produced in-house and the content to which it owns the distribution rights. It’s unclear for now if Netflix would also be scaling back the addition of originals that it didn’t produce, but obtained the rights to — a move that would impact the output of new originals on the service. One of the executives leaving the company is Lisa Nishimura, who was behind the company’s foray into standup comedy and original documentaries, Netflix confirmed. Nishimura had worked on some of Netflix’s most popular titles, including “Making a Murderer,” “Power of the Dog” and “Tiger King.”Ian Bricke, who served as the vice president of Independent Original Film at Netflix, will also be leaving. Bricke played a big part of Netflix’s dominance in the rom-com space, as he spearheaded notable titles like “The Kissing Booth,” “Set It Up” and “To All the Boys I’ve Loved Before.”",
    img : "https://techcrunch.com/wp-content/uploads/2023/03/tiktok-logo-neon.jpg?w=430&h=230&crop=1"
  },
]